// default package
// Generated 23-Aug-2017 18:26:34 by Hibernate Tools 5.2.5.Final

/**
 * Caravan generated by hbm2java
 */
public class Caravan implements java.io.Serializable, ICaravan {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2140854387684407297L;
	private Integer caravanId;
	private String make;
	private String model;
	private Double awnSize;
	private Double internalLength;
	private Double shippingLength;
	private Double fixedBed;
	private Double endBathroom;
	private Double berth;
	private Integer productionYear;
	private Boolean enabled;
	private byte[] comments;

	public Caravan() {
	}

	public Caravan(String make, String model) {
		this.make = make;
		this.model = model;
	}

	public Caravan(String make, String model, Double awnSize, Double internalLength, Double shippingLength,
			Double fixedBed, Double endBathroom, Double berth, Integer productionYear, Boolean enabled,
			byte[] comments) {
		this.make = make;
		this.model = model;
		this.awnSize = awnSize;
		this.internalLength = internalLength;
		this.shippingLength = shippingLength;
		this.fixedBed = fixedBed;
		this.endBathroom = endBathroom;
		this.berth = berth;
		this.productionYear = productionYear;
		this.enabled = enabled;
		this.comments = comments;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getCaravanId()
	 */
	@Override
	public Integer getCaravanId() {
		return this.caravanId;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setCaravanId(java.lang.Integer)
	 */
	@Override
	public void setCaravanId(Integer caravanId) {
		this.caravanId = caravanId;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getMake()
	 */
	@Override
	public String getMake() {
		return this.make;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setMake(java.lang.String)
	 */
	@Override
	public void setMake(String make) {
		this.make = make;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getModel()
	 */
	@Override
	public String getModel() {
		return this.model;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setModel(java.lang.String)
	 */
	@Override
	public void setModel(String model) {
		this.model = model;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getAwnSize()
	 */
	@Override
	public Double getAwnSize() {
		return this.awnSize;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setAwnSize(java.lang.Double)
	 */
	@Override
	public void setAwnSize(Double awnSize) {
		this.awnSize = awnSize;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getInternalLength()
	 */
	@Override
	public Double getInternalLength() {
		return this.internalLength;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setInternalLength(java.lang.Double)
	 */
	@Override
	public void setInternalLength(Double internalLength) {
		this.internalLength = internalLength;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getShippingLength()
	 */
	@Override
	public Double getShippingLength() {
		return this.shippingLength;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setShippingLength(java.lang.Double)
	 */
	@Override
	public void setShippingLength(Double shippingLength) {
		this.shippingLength = shippingLength;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getFixedBed()
	 */
	@Override
	public Double getFixedBed() {
		return this.fixedBed;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setFixedBed(java.lang.Double)
	 */
	@Override
	public void setFixedBed(Double fixedBed) {
		this.fixedBed = fixedBed;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getEndBathroom()
	 */
	@Override
	public Double getEndBathroom() {
		return this.endBathroom;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setEndBathroom(java.lang.Double)
	 */
	@Override
	public void setEndBathroom(Double endBathroom) {
		this.endBathroom = endBathroom;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getBerth()
	 */
	@Override
	public Double getBerth() {
		return this.berth;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setBerth(java.lang.Double)
	 */
	@Override
	public void setBerth(Double berth) {
		this.berth = berth;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getProductionYear()
	 */
	@Override
	public Integer getProductionYear() {
		return this.productionYear;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setProductionYear(java.lang.Integer)
	 */
	@Override
	public void setProductionYear(Integer productionYear) {
		this.productionYear = productionYear;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getEnabled()
	 */
	@Override
	public Boolean getEnabled() {
		return this.enabled;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setEnabled(java.lang.Boolean)
	 */
	@Override
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/* (non-Javadoc)
	 * @see ICaravan#getComments()
	 */
	@Override
	public byte[] getComments() {
		return this.comments;
	}

	/* (non-Javadoc)
	 * @see ICaravan#setComments(byte[])
	 */
	@Override
	public void setComments(byte[] comments) {
		this.comments = comments;
	}

}
