// default package
// Generated 23-Aug-2017 16:14:58 by Hibernate Tools 5.2.5.Final

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable, ICustomer {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8571337674130819055L;
	private Integer customerId;
	private String title;
	private String firstName;
	private String lastName;
	private String address1;
	private String address2;
	private String city;
	private String county;
	private String postCode;
	private String country;
	private String homePhone;
	private String mobilePhone;
	private String email;

	public Customer() {
	}

	public Customer(String firstName, String lastName, String address1, String city, String postCode) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.address1 = address1;
		this.city = city;
		this.postCode = postCode;
	}

	public Customer(String title, String firstName, String lastName, String address1, String address2, String city,
			String county, String postCode, String country, String homePhone, String mobilePhone, String email) {
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.county = county;
		this.postCode = postCode;
		this.country = country;
		this.homePhone = homePhone;
		this.mobilePhone = mobilePhone;
		this.email = email;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getCustomerId()
	 */
	@Override
	public Integer getCustomerId() {
		return this.customerId;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setCustomerId(java.lang.Integer)
	 */
	@Override
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getTitle()
	 */
	@Override
	public String getTitle() {
		return this.title;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setTitle(java.lang.String)
	 */
	@Override
	public void setTitle(String title) {
		this.title = title;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getFirstName()
	 */
	@Override
	public String getFirstName() {
		return this.firstName;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setFirstName(java.lang.String)
	 */
	@Override
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getLastName()
	 */
	@Override
	public String getLastName() {
		return this.lastName;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setLastName(java.lang.String)
	 */
	@Override
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getAddress1()
	 */
	@Override
	public String getAddress1() {
		return this.address1;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setAddress1(java.lang.String)
	 */
	@Override
	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getAddress2()
	 */
	@Override
	public String getAddress2() {
		return this.address2;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setAddress2(java.lang.String)
	 */
	@Override
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getCity()
	 */
	@Override
	public String getCity() {
		return this.city;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setCity(java.lang.String)
	 */
	@Override
	public void setCity(String city) {
		this.city = city;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getCounty()
	 */
	@Override
	public String getCounty() {
		return this.county;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setCounty(java.lang.String)
	 */
	@Override
	public void setCounty(String county) {
		this.county = county;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getPostCode()
	 */
	@Override
	public String getPostCode() {
		return this.postCode;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setPostCode(java.lang.String)
	 */
	@Override
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getCountry()
	 */
	@Override
	public String getCountry() {
		return this.country;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setCountry(java.lang.String)
	 */
	@Override
	public void setCountry(String country) {
		this.country = country;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getHomePhone()
	 */
	@Override
	public String getHomePhone() {
		return this.homePhone;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setHomePhone(java.lang.String)
	 */
	@Override
	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getMobilePhone()
	 */
	@Override
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setMobilePhone(java.lang.String)
	 */
	@Override
	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	/* (non-Javadoc)
	 * @see ICustomer#getEmail()
	 */
	@Override
	public String getEmail() {
		return this.email;
	}

	/* (non-Javadoc)
	 * @see ICustomer#setEmail(java.lang.String)
	 */
	@Override
	public void setEmail(String email) {
		this.email = email;
	}

}
