// default package
// Generated 23-Aug-2017 18:26:34 by Hibernate Tools 5.2.5.Final

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable, IEvent {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1322198595832891652L;
	private Integer eventId;
	private String eventName;
	private String eventLocation;

	public Event() {
	}

	public Event(String eventName, String eventLocation) {
		this.eventName = eventName;
		this.eventLocation = eventLocation;
	}

	/* (non-Javadoc)
	 * @see IEvent#getEventId()
	 */
	@Override
	public Integer getEventId() {
		return this.eventId;
	}

	/* (non-Javadoc)
	 * @see IEvent#setEventId(java.lang.Integer)
	 */
	@Override
	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	/* (non-Javadoc)
	 * @see IEvent#getEventName()
	 */
	@Override
	public String getEventName() {
		return this.eventName;
	}

	/* (non-Javadoc)
	 * @see IEvent#setEventName(java.lang.String)
	 */
	@Override
	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	/* (non-Javadoc)
	 * @see IEvent#getEventLocation()
	 */
	@Override
	public String getEventLocation() {
		return this.eventLocation;
	}

	/* (non-Javadoc)
	 * @see IEvent#setEventLocation(java.lang.String)
	 */
	@Override
	public void setEventLocation(String eventLocation) {
		this.eventLocation = eventLocation;
	}

}
